Созданы ресурсы Вопросов и Тестов
rizh42/RoR_Internship_TestGuru pull request #6
Opened 2020-12-24 17:02 UTC by rizh42

1. Создайте ресурс Вопросов, вложенный в ресурс Тестов

2. Следуя принципам  REST, cоздайте контроллер для ресурса вопросов и реализуйте методы:
   - Просмотра списка вопросов теста
   - Просмотра конкретного вопроса теста
   - Создания вопроса. Используйте шаблон с HTML формой. Идентификатор теста к которому принадлежит вопрос можно указать явно в составе URL значения атрибута action в тэге form
   - Удаления вопроса
   - Используйте метод render внутри действия контроллера чтобы вернуть ответ клиенту как простой текст (plain text) или HTML
   - Используйте обратный вызов при поиске теста в контроллере ресурса вопросов
 
3. Напишите обработку исключения для случая когда вопрос не был найден

2020-12-24 17:21 UTC, VidgarVii requested changes

2020-12-24 17:21 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    if question.valid?
1 запрашивать valid? не имеет смысла.
сразу пробуй сохранить объект. Если сохраниться  - redirect_to. Если нет рендер
2 почему question? я так понимаю результат кода не был проверен

2020-12-24 17:21 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    render inline: '<%= @question %>'
и что в итоге увидит пользователь?

2020-12-24 17:21 UTC, VidgarVii commented on app/views/questions/new.html.erb
> +<%= render 'questions/back_to_questions', test: @test %>
и в место формы я вижу чужой копипаст

2020-12-25 20:48 UTC, VidgarVii requested changes

2020-12-25 20:48 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    render json: @test.questions
Согласно РЕСТ и Rails Way индекс должен возвращать список тестов

2020-12-25 20:48 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +  before_action :find_test, only: %i[index]
ни когда не создавай колбек ради 1 метода. Ухудшает читаемость кода

2020-12-25 20:48 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +  end
и снова нет

2020-12-26 16:48 UTC, rizh42 commented on app/controllers/questions_controller.rb
> +    render json: @test.questions
но это же контроллер вопросов
в чём смысл возвращать список тестов?

2020-12-26 19:57 UTC, merged